export const Currencies = [
	{ name: "United States Dollar", currency: "USD" },
	{ name: "Euro", currency: "EUR" },
	{ name: "British Pound Sterling", currency: "GBP" },
	{ name: "Japanese Yen", currency: "JPY" },
	{ name: "Canadian Dollar", currency: "CAD" },
	{ name: "Australian Dollar", currency: "AUD" },
	{ name: "Swiss Franc", currency: "CHF" },
	{ name: "Chinese Yuan Renminbi", currency: "CNY" },
	{ name: "Indian Rupee", currency: "INR" },
	{ name: "Brazilian Real", currency: "BRL" },
	{ name: "South Korean Won", currency: "KRW" },
	{ name: "Mexican Peso", currency: "MXN" },
	{ name: "Russian Ruble", currency: "RUB" },
	{ name: "South African Rand", currency: "ZAR" },
	{ name: "New Zealand Dollar", currency: "NZD" },
	{ name: "Singapore Dollar", currency: "SGD" },
	{ name: "Hong Kong Dollar", currency: "HKD" },
	{ name: "Norwegian Krone", currency: "NOK" },
	{ name: "Swedish Krona", currency: "SEK" },
	{ name: "Danish Krone", currency: "DKK" },
	{ name: "Turkish Lira", currency: "TRY" },
	{ name: "Saudi Riyal", currency: "SAR" },
	{ name: "United Arab Emirates Dirham", currency: "AED" },
	{ name: "Argentine Peso", currency: "ARS" },
	{ name: "Chilean Peso", currency: "CLP" },
	{ name: "Colombian Peso", currency: "COP" },
	{ name: "Peruvian Sol", currency: "PEN" },
	{ name: "Egyptian Pound", currency: "EGP" },
	{ name: "Israeli Shekel", currency: "ILS" },
	{ name: "Malaysian Ringgit", currency: "MYR" },
	{ name: "Philippine Peso", currency: "PHP" },
	{ name: "Vietnamese Dong", currency: "VND" },
	{ name: "Pakistani Rupee", currency: "PKR" },
	{ name: "Bangladeshi Taka", currency: "BDT" },
	{ name: "Sri Lankan Rupee", currency: "LKR" },
	{ name: "Iraqi Dinar", currency: "IQD" },
	{ name: "Jordanian Dinar", currency: "JOD" },
	{ name: "Kuwaiti Dinar", currency: "KWD" },
	{ name: "Bahraini Dinar", currency: "BHD" },
	{ name: "Omani Rial", currency: "OMR" },
	{ name: "Libyan Dinar", currency: "LYD" },
	{ name: "Sudanese Pound", currency: "SDG" },
	{ name: "Yemeni Rial", currency: "YER" },
	{ name: "Nepalese Rupee", currency: "NPR" },
	{ name: "Tunisian Dinar", currency: "TND" },
	{ name: "Algerian Dinar", currency: "DZD" },
	{ name: "Moroccan Dirham", currency: "MAD" },
	{ name: "Mauritian Rupee", currency: "MUR" },
	{ name: "Seychellois Rupee", currency: "SCR" },
	{ name: "Rwandan Franc", currency: "RWF" },
	{ name: "Burundian Franc", currency: "BIF" },
	{ name: "Ugandan Shilling", currency: "UGX" },
	{ name: "Kenyan Shilling", currency: "KES" },
	{ name: "Tanzanian Shilling", currency: "TZS" },
	{ name: "Ghanaian Cedi", currency: "GHS" },
	{ name: "Zambian Kwacha", currency: "ZMW" },
	{ name: "Zimbabwean Dollar", currency: "ZWL" },
];
